### ISSUE TITLE
Cannot compile in Ubuntu 20 x86_64

### ISSUE THREAD

**Issue by amnesia13** [sifive/freedom-tools#74] opened 2020-12-30 08:02 UTC
Dear all,

I tried to compile the freedom-tools on a HP Probook 650 G1 running Ubuntu 20 x86_64 with i386 support.
After launching make, I get the following error message:

make -C obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-gcc-newlib-stage1/ all-gcc &>obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-gcc-newlib-stage1//make-build.log
 make: *** [Makefile:527 : obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-gcc-newlib-stage1/stamp] Erreur 2

Some clues can be found in the obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-gcc-newlib-stage1//make-build.log file:

checking for CET support... configure: error: in `......freedom-tools/obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-gcc-newlib-stage1/lto-plugin':
configure: error: cannot run test program while cross compiling

Any idea bout the way to fix this ?

Regards

**Comment by jim-wilson** [comment] 2020-12-31 00:23
This is a bug in the upstream FSF GCC sources.  It looks like this was fixed via
    https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94998

The bug doesn't show up on the systems we use for testing because the native gcc doesn't support the -fcf-protection option so we never try to compile and run the testcase.  I was able to reproduce this on Ubuntu 20 though.which has gcc-9 as the system compiler.

**Comment by amnesia13** [comment] 2020-12-31 15:01
Dear Jim,

Thanks for the link and I am going to check if this solves the problem.

Regards

**Comment by jim-wilson** [comment] 2020-12-31 21:18
I was able to build ubuntu64-toolchain with that patch.  I had to do a make clean first as the build system copies the source files into the build tree, and I didn't know offhand how to force that to be redone, so I just did a make clean.  I ran into the problem documented in issue #65 which I worked around by deleting the ubuntu64 --with-python options.

The windows build failed in libusb.  Apparently Ubuntu 20 has a mingw32 pkg-config program that doesn't work with the build.  Ubuntu 18 doesn't have this program, or at least my Ubuntu 18 machine doesn't have it installed.  But I didn't care enough about the windows build to look at that problem.

**Comment by amnesia13** [comment] 2021-01-02 08:43
Dear Jim,

1st of all, a happy new year to you and your family. Following the advice, I installed  GCC 10 on my Ubuntu 20 workstation and apparently I have a working release 10.2. Now I need to point to this GCC version and likely setup some env variables to make it.

Regards

**Comment by lindemer** [comment] 2021-02-17 12:01
Hi all, was this issue ever resolved? I ran into the same problem.

**Comment by jim-wilson** [comment] 2021-02-17 18:22
Probably not fixed yet, but there are workarounds above to get the linux hosted toolchain built.  I don't have a workaround for the windows hosted toolchain as I didn't care enough.

**Closed** 2023-05-04 17:17 UTC
